function hoverRanklist(rankElem){$(".rank_wrap").hover(function(){$(this).parents(".rank").find(".rank_wrap").css({"height":"26px"});$(this).parents(".rank").find(".rank_wrap .rank_wrap_inner").css({"top":"0px"});$(this).find(".rank_wrap_inner").css({"top":"-26px"});$(this).css({"height":"62px"});});$(rankElem).each(function(i,e){$(e).find(".rank_wrap").eq(0).css({"height":"62px"}).find(".rank_wrap_inner").css({"top":"-26px"});});$(".rank_wrap").click(function(e){var href=$(this).attr("href"),statistics=$(this).attr("statistics")?$(this).attr("statistics"):"";if(statistics.length!=0){if(!$(e.target).hasClass("rank_download")){eval(statistics);}}
location.href=href;});}
function changeNumToStar(){$(".star").each(function(i,e){var value=parseInt($(e).attr("number")*10);var fullStar=parseInt(value/20);var emptyStar=value%20;var width=fullStar*14+Math.round(emptyStar*0.3)+3;$(e).find(".fullStar").css({"width":width+"px"})});}
function setMainHeight(lElem,rElem){var height=Math.max($(lElem).outerHeight(true),$(rElem).outerHeight(true));if(height<($(window).height()-134)){height=$(window).height()-134;}
if(!$(rElem).hasClass("detail_main")){height-=50;}
$(rElem).parent("div").css({"height":height+"px"});}
function gotoTop(){if($(document).scrollTop()==0){$(".goto").hide();return;}
if($.browser.version.indexOf("6.0")!=-1){var scrollTop=$(document).scrollTop()+$(window).height()-156;if(scrollTop<0){scrollTop=0;}
$(".goto").css({"top":scrollTop+"px"}).show();}else{$(".goto").css({"bottom":"104px"}).show();}}
function initPage(showNum,currP,totalP,baseURL){var pageArr=computePage(showNum,currP,totalP,baseURL);var fPage='<span>'+pageArr.splice(0,1)+'</span>',lPage='<span>'+pageArr.splice(pageArr.length-1,1)+'</span>',mPage='<span class="pageList">'+pageArr.join("")+'</span>';if(totalP==0){$(".page").html((mPage));}else if(totalP==1){$(".page").html("");}else{$(".page").html((fPage+mPage+lPage));}}
function computePage(showNum,currP,totalP,baseURL){var pageArr=new Array();if(totalP<=showNum){loopPage(1,totalP,currP,baseURL,pageArr);}else{var gap=(showNum-1)/2,lRealGap=currP-1,rRealGap=totalP-currP;if(lRealGap<=gap){loopPage(1,2+gap,currP,baseURL,pageArr);pageArr.push("...");pageArr.push('<a href="'+baseURL+totalP+'">'+totalP+'</a>');}else if(rRealGap<=gap){loopPage(totalP-gap-1,totalP,currP,baseURL,pageArr);pageArr.unshift("...");pageArr.unshift('<a href="'+baseURL+'1">1</a>');}else{pageArr.push('<a href="'+baseURL+'1">1</a>');pageArr.push('...');var tGap=(gap-1)/2;loopPage(currP-tGap,currP-tGap+gap-1,currP,baseURL,pageArr);pageArr.push('...');pageArr.push('<a href="'+baseURL+totalP+'">'+totalP+'</a>');}}
if(currP==1){pageArr.unshift('<a class="quiet" href="javascript:void(0)">上一页</a>');}else{pageArr.unshift('<a href="'+baseURL+(currP-1)+'">上一页</a>');}
if(currP==totalP){pageArr.push('<a class="quiet" href="javascript:void(0)">下一页</a>');}else{pageArr.push('<a href="'+baseURL+(currP+1)+'">下一页</a>');}
return pageArr;}
function loopPage(start,end,currP,baseURL,pageArr){for(var i=start;i<=end;i++){if(i==currP){pageArr.push('<a class="active" href="javascript:void(0)">'+i+'</a>');}else{pageArr.push('<a href="'+baseURL+i+'">'+i+'</a>');}}}
(function($){$.fn.hoverDelay=function(options){var defaults={hoverDuring:200,outDuring:200,hoverEvent:function(){$.noop();},outEvent:function(){$.noop();}};var sets=$.extend(defaults,options||{});var hoverTimer,outTimer,that=this;return $(this).each(function(){$(this).hover(function(){clearTimeout(outTimer);hoverTimer=setTimeout(function(){sets.hoverEvent.apply(that)},sets.hoverDuring);},function(){clearTimeout(hoverTimer);outTimer=setTimeout(function(){sets.outEvent.apply(that)},sets.outDuring);});});}})(jQuery);function AnimateBanner(banners,dot){this.banners=banners,this.dot=dot,this.movement=null,this.circleTime=5000,this.width=792,this.init=function(){var str="";for(var i=0;i<this.banners.length;i++){if(i==0){str+='<span class="active"></span>';}else{str+='<span class="default"></span>';}}
$(".dot").html(str);$(this.banners).not($(this.banners).eq(0)).css({"left":"-"+this.width+"px","display":"block"});this.moveAuto();this.dotHoverBind($(this.dot).find("span"));this.clickChange();this.hoverBanner();},this.animate=function(prev,curr){$(this.dot).find("span").removeClass("active").addClass("default");$(this.dot).find("span").eq(curr).removeClass("default").addClass("active");var sign="";if(prev>curr){sign="-";$(this.banners).eq(curr).css({"left":this.width+"px"});}else{sign="+";$(this.banners).eq(curr).css({"left":"-"+this.width+"px"});}
$(this.banners).eq(prev).animate({left:sign+this.width+"px"},1000);$(this.banners).eq(curr).animate({left:0},1000);},this.moveAuto=function(){this.movement=setInterval(this.autoMoveFunc(this.banners),this.circleTime);},this.autoMoveFunc=function(banners){var that=this;return function(){var prev=$(".dot .active").prevAll().length;var curr=(prev+1)%banners.length;that.animate(prev,curr);}},this.dotHoverBind=function(elems){var that=this;$(elems).each(function(){var thatt=$(this);thatt.hoverDelay({hoverDuring:300,hoverEvent:function(){if($(thatt).hasClass("active")){return;}else{var prev=$(".dot .active").prevAll().length;var curr=$(thatt).prevAll().length;that.animate(prev,curr)}},outEvent:function(){}})})},this.clickChange=function(){var that=this;$(".change").click(function(){if($(this).hasClass("rChange")){var prev=$(".dot .active").prevAll().length;var curr=(prev+1)%banners.length;that.animate(prev,curr)}else{var prev=$(".dot .active").prevAll().length;var curr=(prev-1)%banners.length;that.animate(prev,curr)}});},this.hoverBanner=function(){var that=this;$(".banner").hover(function(){clearInterval(that.movement);},function(){that.moveAuto();});}
this.posBannerImg=function(){$(".banner_img").each(function(i,e){var left=parseInt(($(window).width()-anquan.index.banner_img_width[i])/2);$(e).css({"left":left+"px"});});}}
function showSoftSetDownload(){$(".softSet li").hover(function(){if($(this).parents(".detail_main").length==0){$(this).find(".download").css({"visibility":"visible"});}else{$(this).find(".word").hide().end().find(".download").css({"display":"block"});}},function(){if($(this).parents(".detail_main").length==0){$(this).find(".download").css({"visibility":"hidden"});}else{$(this).find(".download").hide().end().find(".word").css({"display":"block"});}});}
function slidSoftSetPanel(){$(".more").click(function(){if($(this).parents(".softSet").find("li").length<=12){return false;}
if($(this).hasClass("slid")){$(this).removeClass("slid").html("更多&nbsp;<span class='flag'></span>");$(this).parents(".softSet").css({"height":"370px"});}else{$(this).addClass("slid").html("收起&nbsp;<span class='flag'></span>");$(this).parents(".softSet").css({"height":"auto"});}
setMainHeight($(".index_softHolder"),$(".index_sideBar"));});}
function hoverNavList(){$(".navList").find("a").parents("li").hover(function(){if($(this).find("span").hasClass("active")){return;}else{$(this).find("span").addClass("hover");}},function(){if($(this).find("span").hasClass("active")){return;}else{$(this).find("span").removeClass("hover");}});}
function focusSearchBar(){if($(".searchArea").length<1){return false;}
$(".searchArea").focus(function(){$(this).addClass("searchAreaActive");});$(".searchArea").blur(function(){$(this).removeClass("searchAreaActive");});}
function strlen(str)
{var i;var len;len=0;for(i=0;i<str.length;i++)
{if(str.charCodeAt(i)>255)len+=2;else len++;}
return len;}